### PR TITLE
Voting poll

### PR DESCRIPTION
**Pull request by vomaxHELLnO**
Issues: #44 and #45

### CODE REVIEW

**Comment by sirex** [comment]
Please do not forget to specify what task this pull request implements.

**Comment by sirex** [comment]
And it looks like this pull request is mixed with #35.

**Comment by vomaxHELLnO** [comment]
Very strange, migrations fail with ```django.db.utils.ProgrammingError: relation "core_project" does not exist``` error, when trying to add ```ForeignKey``` to ```Project``` model. But everything works fine, when ```ForeignKey``` to any other model is added. Any ideas, what's happening?

**Comment by sirex** [comment]
Master does not have this fix.

**Comment by niekas** [comment]
Strange TravisCI error: failed to download https://github.com/twbs/bootstrap/releases/download/v3.3.1/bootstrap-3.3.1-dist.zip

**Comment by iakovleva** [comment]
The same issue with bootstrap downloading in #48

**Pull request merged**
