### PR TITLE
Attendance model

### PR DESCRIPTION
**Pull request by Euphorbium**
#25 Should I also make a form and display it? Is email sending configured?

### CODE REVIEW

**Comment by Euphorbium** [comment]
Should I include migrations file?

**Comment by sirex** [comment]
Why this pull request was closed?

> Should I also make a form and display it?

Yes.

> Is email sending configured?

By default Django sends emails via localhost:25 smtp server. pylab.lt server has configured localhost:25 smtp server.

> Should I include migrations file?

Yes.

**Comment by Euphorbium** [comment]
I closed it to add migrations. Can I modify a pull request? Add some commits to it?

**Comment by sirex** [comment]
> Can I modify a pull request? Add some commits to it?

While pull request is not closed or merged, you can modify it, just committing and pushing same branch, pull request will be updated automatically with new commits.

**Pull request closed without merging**
