### PR TITLE
Add new images for landing page and delete dummy ones

### PR DESCRIPTION
**Pull request by iakovleva**
@niekas I also need your image with python duck :)

### CODE REVIEW

**Comment by sirex** [comment]
@niekas your skills with images are improving! :)

@iakovleva I just glanced at landing page and image there are way to big and does not fit into provided spaces, this need to be fixed.

You can generate correct size images for svg files or you can use https://github.com/mariocesar/sorl-thumbnail, this will let you adjust image size much more easily, but will degrade image quality a bit (compared to creating images from svg).

**Comment by niekas** [comment]
@sirex They are not |: I just refactored this image http://media-cache-ak0.pinimg.com/736x/31/45/e2/3145e2e390d2a66720c3c9fb8a1cadab.jpg . I'll probably have to redraw it.

**Comment by iakovleva** [comment]
I think it would be better to link to the list of events from main page, not from about page.

**Comment by sirex** [comment]
@niekas on the duck image I see a © sign, is this your creation or someone's else?

@iakovleva I agree, that at least 3 closest future events should be shown on landing page.

**Comment by niekas** [comment]
@sirex Well the original image is someone's else creation, but its low quality jpg. I've created similar SVG image. These two images may be too similar, so I'll probably redraw it.

**Comment by sirex** [comment]
I posted few comments, but other than that it looks good to me and can be merged.

**Pull request merged**
